spring:
  application:
    name: com.cloud.eureka-service-zuul


eureka:
  client:
    serviceurl:
      defaultZone: http://localhost:8080/eureka/


server:
  port: 8095


zuul:
  routes:
    hello:
      path: /test/**
      serviceId: com.cloud.eureka-service-client
